# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65db7e10580944b61bcc670ab4764a9b712dda626aae45787278c8df1ef86c6ae405ca445f8fade4bea38e4e6fb488fba04a3a070ecd20ac16ed10765db8f5ec

test:
  secret_key_base: 5049ac5615fed6b66ccfc2456d0ece599decfb4f9951ce358d90198a7966783df65b0ace05e4ab3760e740d836a32fb1e723f0e6529e86ae879db89949cb10c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
